### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by Marbyun** [rizkynajwa/OCR-KTP-Indonesia#2]
bang cara running nya gmna? di postman parameters dikasih apa bang

**Comment by rizkynajwa** [comment]
Bisa mengikuti langkah-langkah yang ada di readme ya. Kalau menggunakan Postman, nanti yang diupload adalah file foto KTP, bisa mengikuti tutorial di link ini https://apidog.com/blog/postman-upload-file-detailed-guide/

**Comment by Marbyun** [comment]
sip thank you bang
